title: Aparna Raghavendra Rao
logo: images/aparna_headshot.jpeg
description: Data Analyst | Passionate about storytelling with data for business impact
show_downloads: true 
theme: jekyll-theme-minimal
